### ISSUE TITLE
Remove devices from here since they are move to the devices repo ???

### ISSUE THREAD

**Issue by applemuncy** [ubports/android#5]
"{Remove devices from here since they are move to the devices repo"

Is there some explanation somewhere that explains the current ubports method of compiling, for say, hammerhead?  How is the build for hammerhead on devel_rc-proposed setup?

**Comment by applemuncy** [comment]
Maybe we could  have a .repo/manifest/devices directory containing [   manufacturer]_[device].xml files that could then be selected by adding a symlink in .repo/local_manifest/ ?

**Comment by UniversalSuperBox** [comment]
This repository is correct, and is the manifest for all UBPorts devices.

It's possible that we could use tagging and branches in the future to reduce download size, but initializing the repository with `repo init --depth=1` seems to reduce the download size much better than removing things from the manifest.

**Comment by UniversalSuperBox** [comment]
Wow, I'm an idiot. The devices/ repository isn't used for developing yet, but I assume that Jenkins pulls it.
